-- pkmn_g1_data.lua
-- A listing of all pokemon and moves by index number

-- POKEMON BY INDEX
-- Table contains tables
-- [i].sprite  = image file name
-- [i].name  = pokemon's name
-- contains 2nd gen equivalents where valid
-- Data provided by Bulbapedia

local pokemon_by_index  = {
	[0]= {sprite="Box_Sprites/000.png", name="None"},
	[1]= {sprite="Box_Sprites/112.png", name="Rhydon"},
	[2]= {sprite="Box_Sprites/115.png", name="Kangaskhan"},
	[3]= {sprite="Box_Sprites/032.png", name="Nidoran♂"},
	[4]= {sprite="Box_Sprites/035.png", name="Clefairy"},
	[5]= {sprite="Box_Sprites/021.png", name="Spearow"},
	[6]= {sprite="Box_Sprites/100.png", name="Voltorb"},
	[7]= {sprite="Box_Sprites/034.png", name="Nidoking"},
	[8]= {sprite="Box_Sprites/080.png", name="Slowbro"},
	[9]= {sprite="Box_Sprites/002.png", name="Ivysaur"},
	[10]= {sprite="Box_Sprites/103.png", name="Exeggutor"},
	[11]= {sprite="Box_Sprites/108.png", name="Lickitung"},
	[12]= {sprite="Box_Sprites/102.png", name="Exeggcute"},
	[13]= {sprite="Box_Sprites/088.png", name="Grimer"},
	[14]= {sprite="Box_Sprites/094.png", name="Gengar"},
	[15]= {sprite="Box_Sprites/029.png", name="Nidoran♀"},
	[16]= {sprite="Box_Sprites/031.png", name="Nidoqueen"},
	[17]= {sprite="Box_Sprites/104.png", name="Cubone"},
	[18]= {sprite="Box_Sprites/111.png", name="Rhyhorn"},
	[19]= {sprite="Box_Sprites/131.png", name="Lapras"},
	[20]= {sprite="Box_Sprites/059.png", name="Arcanine"},
	[21]= {sprite="Box_Sprites/151.png", name="Mew"},
	[22]= {sprite="Box_Sprites/130.png", name="Gyarados"},
	[23]= {sprite="Box_Sprites/090.png", name="Shellder"},
	[24]= {sprite="Box_Sprites/072.png", name="Tentacool"},
	[25]= {sprite="Box_Sprites/092.png", name="Gastly"},
	[26]= {sprite="Box_Sprites/123.png", name="Scyther"},
	[27]= {sprite="Box_Sprites/120.png", name="Staryu"},
	[28]= {sprite="Box_Sprites/009.png", name="Blastoise"},
	[29]= {sprite="Box_Sprites/127.png", name="Pinsir"},
	[30]= {sprite="Box_Sprites/114.png", name="Tangela"},
	[31]= {sprite="Box_Sprites/212.png", name="Scizor"},
	[32]= {sprite="Box_Sprites/213.png", name="Shuckle"},
	[33]= {sprite="Box_Sprites/058.png", name="Growlithe"},
	[34]= {sprite="Box_Sprites/095.png", name="Onix"},
	[35]= {sprite="Box_Sprites/022.png", name="Fearow"},
	[36]= {sprite="Box_Sprites/016.png", name="Pidgey"},
	[37]= {sprite="Box_Sprites/079.png", name="Slowpoke"},
	[38]= {sprite="Box_Sprites/064.png", name="Kadabra"},
	[39]= {sprite="Box_Sprites/075.png", name="Graveler"},
	[40]= {sprite="Box_Sprites/113.png", name="Chansey"},
	[41]= {sprite="Box_Sprites/067.png", name="Machoke"},
	[42]= {sprite="Box_Sprites/122.png", name="Mr. Mime"},
	[43]= {sprite="Box_Sprites/106.png", name="Hitmonlee"},
	[44]= {sprite="Box_Sprites/107.png", name="Hitmonchan"},
	[45]= {sprite="Box_Sprites/024.png", name="Arbok"},
	[46]= {sprite="Box_Sprites/047.png", name="Parasect"},
	[47]= {sprite="Box_Sprites/054.png", name="Psyduck"},
	[48]= {sprite="Box_Sprites/096.png", name="Drowzee"},
	[49]= {sprite="Box_Sprites/076.png", name="Golem"},
	[50]= {sprite="Box_Sprites/214.png", name="Heracross"},
	[51]= {sprite="Box_Sprites/126.png", name="Magmar"},
	[52]= {sprite="Box_Sprites/250.png", name="Ho-Oh"},
	[53]= {sprite="Box_Sprites/125.png", name="Electabuzz"},
	[54]= {sprite="Box_Sprites/082.png", name="Magneton"},
	[55]= {sprite="Box_Sprites/109.png", name="Koffing"},
	[56]= {sprite="Box_Sprites/215.png", name="Sneasel"},
	[57]= {sprite="Box_Sprites/056.png", name="Mankey"},
	[58]= {sprite="Box_Sprites/086.png", name="Seel"},
	[59]= {sprite="Box_Sprites/050.png", name="Diglett"},
	[60]= {sprite="Box_Sprites/128.png", name="Tauros"},
	[61]= {sprite="Box_Sprites/216.png", name="Teddiursa"},
	[62]= {sprite="Box_Sprites/217.png", name="Ursaring"},
	[63]= {sprite="Box_Sprites/218.png", name="Slugma"},
	[64]= {sprite="Box_Sprites/083.png", name="Farfetchd"},
	[65]= {sprite="Box_Sprites/048.png", name="Venonat"},
	[66]= {sprite="Box_Sprites/149.png", name="Dragonite"},
	[67]= {sprite="Box_Sprites/219.png", name="Magcargo"},
	[68]= {sprite="Box_Sprites/220.png", name="Swinub"},
	[69]= {sprite="Box_Sprites/221.png", name="Piloswine"},
	[70]= {sprite="Box_Sprites/084.png", name="Doduo"},
	[71]= {sprite="Box_Sprites/060.png", name="Poliwag"},
	[72]= {sprite="Box_Sprites/124.png", name="Jynx"},
	[73]= {sprite="Box_Sprites/146.png", name="Moltres"},
	[74]= {sprite="Box_Sprites/144.png", name="Articuno"},
	[75]= {sprite="Box_Sprites/145.png", name="Zapdos"},
	[76]= {sprite="Box_Sprites/132.png", name="Ditto"},
	[77]= {sprite="Box_Sprites/052.png", name="Meowth"},
	[78]= {sprite="Box_Sprites/098.png", name="Krabby"},
	[79]= {sprite="Box_Sprites/222.png", name="Corsola"},
	[80]= {sprite="Box_Sprites/223.png", name="Remoraid"},
	[81]= {sprite="Box_Sprites/224.png", name="Octillery"},
	[82]= {sprite="Box_Sprites/037.png", name="Vulpix"},
	[83]= {sprite="Box_Sprites/038.png", name="Ninetales"},
	[84]= {sprite="Box_Sprites/025.png", name="Pikachu"},
	[85]= {sprite="Box_Sprites/026.png", name="Raichu"},
	[86]= {sprite="Box_Sprites/225.png", name="Delibird"},
	[87]= {sprite="Box_Sprites/226.png", name="Mantine"},
	[88]= {sprite="Box_Sprites/147.png", name="Dratini"},
	[89]= {sprite="Box_Sprites/148.png", name="Dragonair"},
	[90]= {sprite="Box_Sprites/140.png", name="Kabuto"},
	[91]= {sprite="Box_Sprites/141.png", name="Kabutops"},
	[92]= {sprite="Box_Sprites/116.png", name="Horsea"},
	[93]= {sprite="Box_Sprites/117.png", name="Seadra"},
	[94]= {sprite="Box_Sprites/227.png", name="Skarmory"},
	[95]= {sprite="Box_Sprites/228.png", name="Houndour"},
	[96]= {sprite="Box_Sprites/027.png", name="Sandshrew"},
	[97]= {sprite="Box_Sprites/028.png", name="Sandslash"},
	[98]= {sprite="Box_Sprites/138.png", name="Omanyte"},
	[99]= {sprite="Box_Sprites/139.png", name="Omastar"},
	[100]= {sprite="Box_Sprites/039.png", name="Jigglypuff"},
	[101]= {sprite="Box_Sprites/040.png", name="Wigglytuff"},
	[102]= {sprite="Box_Sprites/133.png", name="Eevee"},
	[103]= {sprite="Box_Sprites/136.png", name="Flareon"},
	[104]= {sprite="Box_Sprites/135.png", name="Jolteon"},
	[105]= {sprite="Box_Sprites/134.png", name="Vaporeon"},
	[106]= {sprite="Box_Sprites/066.png", name="Machop"},
	[107]= {sprite="Box_Sprites/041.png", name="Zubat"},
	[108]= {sprite="Box_Sprites/023.png", name="Ekans"},
	[109]= {sprite="Box_Sprites/046.png", name="Paras"},
	[110]= {sprite="Box_Sprites/061.png", name="Poliwhirl"},
	[111]= {sprite="Box_Sprites/062.png", name="Poliwrath"},
	[112]= {sprite="Box_Sprites/013.png", name="Weedle"},
	[113]= {sprite="Box_Sprites/014.png", name="Kakuna"},
	[114]= {sprite="Box_Sprites/015.png", name="Beedrill"},
	[115]= {sprite="Box_Sprites/229.png", name="Houndoom"},
	[116]= {sprite="Box_Sprites/085.png", name="Dodrio"},
	[117]= {sprite="Box_Sprites/057.png", name="Primeape"},
	[118]= {sprite="Box_Sprites/051.png", name="Dugtrio"},
	[119]= {sprite="Box_Sprites/049.png", name="Venomoth"},
	[120]= {sprite="Box_Sprites/087.png", name="Dewgong"},
	[121]= {sprite="Box_Sprites/230.png", name="Kingdra"},
	[122]= {sprite="Box_Sprites/231.png", name="Phanpy"},
	[123]= {sprite="Box_Sprites/010.png", name="Caterpie"},
	[124]= {sprite="Box_Sprites/011.png", name="Metapod"},
	[125]= {sprite="Box_Sprites/012.png", name="Butterfree"},
	[126]= {sprite="Box_Sprites/068.png", name="Machamp"},
	[127]= {sprite="Box_Sprites/232.png", name="Donphan"},
	[128]= {sprite="Box_Sprites/055.png", name="Golduck"},
	[129]= {sprite="Box_Sprites/097.png", name="Hypno"},
	[130]= {sprite="Box_Sprites/042.png", name="Golbat"},
	[131]= {sprite="Box_Sprites/150.png", name="Mewtwo"},
	[132]= {sprite="Box_Sprites/143.png", name="Snorlax"},
	[133]= {sprite="Box_Sprites/129.png", name="Magikarp"},
	[134]= {sprite="Box_Sprites/233.png", name="Porygon2"},
	[135]= {sprite="Box_Sprites/234.png", name="Stantler"},
	[136]= {sprite="Box_Sprites/089.png", name="Muk"},
	[137]= {sprite="Box_Sprites/235.png", name="Smeargle"},
	[138]= {sprite="Box_Sprites/099.png", name="Kingler"},
	[139]= {sprite="Box_Sprites/091.png", name="Cloyster"},
	[140]= {sprite="Box_Sprites/236.png", name="Tyrogue"},
	[141]= {sprite="Box_Sprites/101.png", name="Electrode"},
	[142]= {sprite="Box_Sprites/036.png", name="Clefable"},
	[143]= {sprite="Box_Sprites/110.png", name="Weezing"},
	[144]= {sprite="Box_Sprites/053.png", name="Persian"},
	[145]= {sprite="Box_Sprites/105.png", name="Marowak"},
	[146]= {sprite="Box_Sprites/237.png", name="Hitmontop"},
	[147]= {sprite="Box_Sprites/093.png", name="Haunter"},
	[148]= {sprite="Box_Sprites/063.png", name="Abra"},
	[149]= {sprite="Box_Sprites/065.png", name="Alakazam"},
	[150]= {sprite="Box_Sprites/017.png", name="Pidgeotto"},
	[151]= {sprite="Box_Sprites/018.png", name="Pidgeot"},
	[152]= {sprite="Box_Sprites/121.png", name="Starmie"},
	[153]= {sprite="Box_Sprites/001.png", name="Bulbasaur"},
	[154]= {sprite="Box_Sprites/003.png", name="Venusaur"},
	[155]= {sprite="Box_Sprites/073.png", name="Tentacruel"},
	[156]= {sprite="Box_Sprites/238.png", name="Smoochum"},
	[157]= {sprite="Box_Sprites/118.png", name="Goldeen"},
	[158]= {sprite="Box_Sprites/119.png", name="Seaking"},
	[159]= {sprite="Box_Sprites/239.png", name="Elekid"},
	[160]= {sprite="Box_Sprites/240.png", name="Magby"},
	[161]= {sprite="Box_Sprites/241.png", name="Miltank"},
	[162]= {sprite="Box_Sprites/242.png", name="Blissey"},
	[163]= {sprite="Box_Sprites/077.png", name="Ponyta"},
	[164]= {sprite="Box_Sprites/078.png", name="Rapidash"},
	[165]= {sprite="Box_Sprites/019.png", name="Rattata"},
	[166]= {sprite="Box_Sprites/020.png", name="Raticate"},
	[167]= {sprite="Box_Sprites/033.png", name="Nidorino"},
	[168]= {sprite="Box_Sprites/030.png", name="Nidorina"},
	[169]= {sprite="Box_Sprites/074.png", name="Geodude"},
	[170]= {sprite="Box_Sprites/137.png", name="Porygon"},
	[171]= {sprite="Box_Sprites/142.png", name="Aerodactyl"},
	[172]= {sprite="Box_Sprites/243.png", name="Raikou"},
	[173]= {sprite="Box_Sprites/081.png", name="Magnemite"},
	[174]= {sprite="Box_Sprites/244.png", name="Entei"},
	[175]= {sprite="Box_Sprites/245.png", name="Suicune"},
	[176]= {sprite="Box_Sprites/004.png", name="Charmander"},
	[177]= {sprite="Box_Sprites/007.png", name="Squirtle"},
	[178]= {sprite="Box_Sprites/005.png", name="Charmeleon"},
	[179]= {sprite="Box_Sprites/008.png", name="Wartortle"},
	[180]= {sprite="Box_Sprites/006.png", name="Charizard"},
	[181]= {sprite="Box_Sprites/246.png", name="Larvitar"},
	[182]= {sprite="Box_Sprites/247.png", name="Pupitar"},
	[183]= {sprite="Box_Sprites/248.png", name="Tyranitar"},
	[184]= {sprite="Box_Sprites/249.png", name="Lugia"},
	[185]= {sprite="Box_Sprites/043.png", name="Oddish"},
	[186]= {sprite="Box_Sprites/044.png", name="Gloom"},
	[187]= {sprite="Box_Sprites/045.png", name="Vileplume"},
	[188]= {sprite="Box_Sprites/069.png", name="Bellsprout"},
	[189]= {sprite="Box_Sprites/070.png", name="Weepinbell"},
	[190]= {sprite="Box_Sprites/071.png", name="Victreebel"},
	[191]= {sprite="Box_Sprites/152.png", name="Chikorita"},
	[192]= {sprite="Box_Sprites/153.png", name="Bayleef"},
	[193]= {sprite="Box_Sprites/154.png", name="Meganium"},
	[194]= {sprite="Box_Sprites/155.png", name="Cyndaquil"},
	[195]= {sprite="Box_Sprites/156.png", name="Quilava"},
	[196]= {sprite="Box_Sprites/157.png", name="Typhlosion"},
	[197]= {sprite="Box_Sprites/158.png", name="Totodile"},
	[198]= {sprite="Box_Sprites/159.png", name="Croconaw"},
	[199]= {sprite="Box_Sprites/160.png", name="Feraligatr"},
	[200]= {sprite="Box_Sprites/161.png", name="Sentret"},
	[201]= {sprite="Box_Sprites/162.png", name="Furret"},
	[202]= {sprite="Box_Sprites/163.png", name="Hoothoot"},
	[203]= {sprite="Box_Sprites/164.png", name="Noctowl"},
	[204]= {sprite="Box_Sprites/165.png", name="Ledyba"},
	[205]= {sprite="Box_Sprites/166.png", name="Ledian"},
	[206]= {sprite="Box_Sprites/167.png", name="Spinarak"},
	[207]= {sprite="Box_Sprites/168.png", name="Ariados"},
	[208]= {sprite="Box_Sprites/169.png", name="Crobat"},
	[209]= {sprite="Box_Sprites/170.png", name="Chinchou"},
	[210]= {sprite="Box_Sprites/171.png", name="Lanturn"},
	[211]= {sprite="Box_Sprites/172.png", name="Pichu"},
	[212]= {sprite="Box_Sprites/173.png", name="Cleffa"},
	[213]= {sprite="Box_Sprites/174.png", name="Igglybuff"},
	[214]= {sprite="Box_Sprites/175.png", name="Togepi"},
	[215]= {sprite="Box_Sprites/176.png", name="Togetic"},
	[216]= {sprite="Box_Sprites/177.png", name="Natu"},
	[217]= {sprite="Box_Sprites/178.png", name="Xatu"},
	[218]= {sprite="Box_Sprites/179.png", name="Mareep"},
	[219]= {sprite="Box_Sprites/180.png", name="Flaaffy"},
	[220]= {sprite="Box_Sprites/181.png", name="Ampharos"},
	[221]= {sprite="Box_Sprites/182.png", name="Bellossom"},
	[222]= {sprite="Box_Sprites/183.png", name="Marill"},
	[223]= {sprite="Box_Sprites/184.png", name="Azumarill"},
	[224]= {sprite="Box_Sprites/185.png", name="Sudowoodo"},
	[225]= {sprite="Box_Sprites/186.png", name="Politoed"},
	[226]= {sprite="Box_Sprites/187.png", name="Hoppip"},
	[227]= {sprite="Box_Sprites/188.png", name="Skiploom"},
	[228]= {sprite="Box_Sprites/189.png", name="Jumpluff"},
	[229]= {sprite="Box_Sprites/190.png", name="Aipom"},
	[230]= {sprite="Box_Sprites/191.png", name="Sunkern"},
	[231]= {sprite="Box_Sprites/192.png", name="Sunflora"},
	[232]= {sprite="Box_Sprites/193.png", name="Yanma"},
	[233]= {sprite="Box_Sprites/194.png", name="Wooper"},
	[234]= {sprite="Box_Sprites/195.png", name="Quagsire"},
	[235]= {sprite="Box_Sprites/196.png", name="Espeon"},
	[236]= {sprite="Box_Sprites/197.png", name="Umbreon"},
	[237]= {sprite="Box_Sprites/198.png", name="Murkrow"},
	[238]= {sprite="Box_Sprites/199.png", name="Slowking"},
	[239]= {sprite="Box_Sprites/200.png", name="Misdreavus"},
	[240]= {sprite="Box_Sprites/201.png", name="Unown"},
	[241]= {sprite="Box_Sprites/202.png", name="Wobbuffet"},
	[242]= {sprite="Box_Sprites/203.png", name="Girafarig"},
	[243]= {sprite="Box_Sprites/204.png", name="Pineco"},
	[244]= {sprite="Box_Sprites/205.png", name="Forretress"},
	[245]= {sprite="Box_Sprites/206.png", name="Dunsparce"},
	[246]= {sprite="Box_Sprites/207.png", name="Gligar"},
	[247]= {sprite="Box_Sprites/208.png", name="Steelix"},
	[248]= {sprite="Box_Sprites/209.png", name="Snubbull"},
	[249]= {sprite="Box_Sprites/210.png", name="Granbull"},
	[250]= {sprite="Box_Sprites/211.png", name="Qwilfish"},
	[251]= {sprite="Box_Sprites/000.png", name="None"},
	[252]= {sprite="Box_Sprites/000.png", name="None"},
	[253]= {sprite="Box_Sprites/000.png", name="None"},
	[254]= {sprite="Box_Sprites/000.png", name="None"},
	[255]= {sprite="Box_Sprites/000.png", name="None"}
}

-- Moves by index

local moves_by_index  = {
	[1]  = "Pound",
	[2]  = "Karate Chop",
	[3]  = "Double Slap",
	[4]  = "Comet Punch",
	[5]  = "Mega Punch",
	[6]  = "Pay Day",
	[7]  = "Fire Punch",
	[8]  = "Ice Punch",
	[9]  = "Thunder Punch",
	[10]  = "Scratch",
	[11]  = "Vice Grip",
	[12]  = "Guillotine",
	[13]  = "Razor Wind",
	[14]  = "Swords Dance",
	[15]  = "Cut",
	[16]  = "Gust",
	[17]  = "Wing Attack",
	[18]  = "Whirlwind",
	[19]  = "Fly",
	[20]  = "Bind",
	[21]  = "Slam",
	[22]  = "Vine Whip",
	[23]  = "Stomp",
	[24]  = "Double Kick",
	[25]  = "Mega Kick",
	[26]  = "Jump Kick",
	[27]  = "Rolling Kick",
	[28]  = "Sand Attack",
	[29]  = "Headbutt",
	[30]  = "Horn Attack",
	[31]  = "Fury Attack",
	[32]  = "Horn Drill",
	[33]  = "Tackle",
	[34]  = "Body Slam",
	[35]  = "Wrap",
	[36]  = "Take Down",
	[37]  = "Thrash",
	[38]  = "Double-Edge",
	[39]  = "Tail Whip",
	[40]  = "Poison Sting",
	[41]  = "Twineedle",
	[42]  = "Pin Missile",
	[43]  = "Leer",
	[44]  = "Bite",
	[45]  = "Growl",
	[46]  = "Roar",
	[47]  = "Sing",
	[48]  = "Supersonic",
	[49]  = "Sonic Boom",
	[50]  = "Disable",
	[51]  = "Acid",
	[52]  = "Ember",
	[53]  = "Flamethrower",
	[54]  = "Mist",
	[55]  = "Water Gun",
	[56]  = "Hydro Pump",
	[57]  = "Surf",
	[58]  = "Ice Beam",
	[59]  = "Blizzard",
	[60]  = "Psybeam",
	[61]  = "Bubble Beam",
	[62]  = "Aurora Beam",
	[63]  = "Hyper Beam",
	[64]  = "Peck",
	[65]  = "Drill Peck",
	[66]  = "Submission",
	[67]  = "Low Kick",
	[68]  = "Counter",
	[69]  = "Seismic Toss",
	[70]  = "Strength",
	[71]  = "Absorb",
	[72]  = "Mega Drain",
	[73]  = "Leech Seed",
	[74]  = "Growth",
	[75]  = "Razor Leaf",
	[76]  = "Solar Beam",
	[77]  = "Poison Powder",
	[78]  = "Stun Spore",
	[79]  = "Sleep Powder",
	[80]  = "Petal Dance",
	[81]  = "String Shot",
	[82]  = "Dragon Rage",
	[83]  = "Fire Spin",
	[84]  = "Thunder Shock",
	[85]  = "Thunderbolt",
	[86]  = "Thunder Wave",
	[87]  = "Thunder",
	[88]  = "Rock Throw",
	[89]  = "Earthquake",
	[90]  = "Fissure",
	[91]  = "Dig",
	[92]  = "Toxic",
	[93]  = "Confusion",
	[94]  = "Psychic",
	[95]  = "Hypnosis",
	[96]  = "Meditate",
	[97]  = "Agility",
	[98]  = "Quick Attack",
	[99]  = "Rage",
	[100]  = "Teleport",
	[101]  = "Night Shade",
	[102]  = "Mimic",
	[103]  = "Screech",
	[104]  = "Double Team",
	[105]  = "Recover",
	[106]  = "Harden",
	[107]  = "Minimize",
	[108]  = "Smokescreen",
	[109]  = "Confuse Ray",
	[110]  = "Withdraw",
	[111]  = "Defense Curl",
	[112]  = "Barrier",
	[113]  = "Light Screen",
	[114]  = "Haze",
	[115]  = "Reflect",
	[116]  = "Focus Energy",
	[117]  = "Bide",
	[118]  = "Metronome",
	[119]  = "Mirror Move",
	[120]  = "Self-Destruct",
	[121]  = "Egg Bomb",
	[122]  = "Lick",
	[123]  = "Smog",
	[124]  = "Sludge",
	[125]  = "Bone Club",
	[126]  = "Fire Blast",
	[127]  = "Waterfall",
	[128]  = "Clamp",
	[129]  = "Swift",
	[130]  = "Skull Bash",
	[131]  = "Spike Cannon",
	[132]  = "Constrict",
	[133]  = "Amnesia",
	[134]  = "Kinesis",
	[135]  = "Soft-Boiled",
	[136]  = "High Jump Kick",
	[137]  = "Glare",
	[138]  = "Dream Eater",
	[139]  = "Poison Gas",
	[140]  = "Barrage",
	[141]  = "Leech Life",
	[142]  = "Lovely Kiss",
	[143]  = "Sky Attack",
	[144]  = "Transform",
	[145]  = "Bubble",
	[146]  = "Dizzy Punch",
	[147]  = "Spore",
	[148]  = "Flash",
	[149]  = "Psywave",
	[150]  = "Splash",
	[151]  = "Acid Armor",
	[152]  = "Crabhammer",
	[153]  = "Explosion",
	[154]  = "Fury Swipes",
	[155]  = "Bonemerang",
	[156]  = "Rest",
	[157]  = "Rock Slide",
	[158]  = "Hyper Fang",
	[159]  = "Sharpen",
	[160]  = "Conversion",
	[161]  = "Tri Attack",
	[162]  = "Super Fang",
	[163]  = "Slash",
	[164]  = "Substitute",
	[165]  = "Struggle"
}

function getPokemonByIndex(index)
	if index < 256 then
		return pokemon_by_index[index]
	else
		console.log(debug.traceback())
		error("Error in getPokemonByIndex: Invalid index (was not passed a byte)", 2)
	end
end

function getMoveByIndex(index)
	if index < 166 then
		return moves_by_index[index]
	else
		console.log(debug.traceback())
		error("Error in getMoveByIndex: Invalid index (should be less than 166)", 2)
	end
end


console.log("Now verifying that the script loaded properly.")
console.log("You should now see Gastly and Mega Kick on the next two lines.")
console.log(getPokemonByIndex(25).name)
console.log(getMoveByIndex(25))